### PR TITLE
test: http static site access

### PR DESCRIPTION
**Pull request by rpoisel**
Hi, I was about to fix the issue with the HTTP UI, but you were faster than me. :-) Thanks for fixing it!

I started by creating a rudimentary suite of tests (I almost always fix/implement stuff test-driven). Maybe it is helpful for you too.

### CODE REVIEW

**Comment by andig** [comment]
Can you please limit the changes to the necessary amount?

**Comment by rpoisel** [comment]
> Can you please limit the changes to the necessary amount?

Oh, sorry. Sure! I was not aware that modules are not "vendored" in this repository.

**Comment by andig** [comment]
@rpoisel PR is rebased but the test fails. Cold you take a look?

**Comment by rpoisel** [comment]
> @rpoisel PR is rebased but the test fails. Cold you take a look?

Hi @andig, I will! Please give me 1-2 days to do that. I'm a bit busy for the moment.

**Comment by rpoisel** [comment]
> @rpoisel PR is rebased but the test fails. Cold you take a look?

Sorry, took me a bit longer. I rebased the branch to the current `master` branch and changed the test to use a `httptest.ResponseRecorder` to look into the web interface of mbmd. So, no more TCP ports needed for the test.

In order to achieve this goal, I had to change the calling interface of `server.Httpd` a bit (imo it now distinguishes a bit better between instantiation and running).

**Comment by andig** [comment]
Great PR, thank you!

**Pull request merged**
