### PR TITLE
Sanitize models and increase timeout

### PR DESCRIPTION
**Pull request by servo77**
Increase timeout to let build on RPi finish

Sanitize models, removing 113 if 103 is present. Observed on Kostal Plenticore, which causes avg values to get corrupted. Possibly due to missing Battery (no way to check).

### CODE REVIEW

**Comment by andig** [comment]
Imho you can have 103 and 113 both. No point in arbitrarily removing one of them. Probably need another mechanism to chose which one should be published. Or talk to the manufacturer why one them apparently delivers corrupted data.

**Comment by servo77** [comment]
Btw, this was a fix of the issue #168 which you closed, I'm getting exactly same problem. Is adding this code as part of Kostal fix a good approach? Or we can investigate assumption about encoding issue.

**Comment by servo77** [comment]
I  should have explained the main issue in more detail. The /avg values from 103 I use from mbmd are getting distorted by the values from model 113, cause they have same names (I believe), but totally wild values. Hence this attempt to get clean 103 avg values by removing the 113. If you see a better way of solving this, welcome to share.

**Comment by andig** [comment]
The issue is imho that both models could (and should!) deliver valid data. We need a mechanism of chosing which one to use as they yield identical measurements. The simple approach of "always use a if a and b are present" is imho not enough.

**Comment by servo77** [comment]
Not actively. Found no API doc on Kostal site. What about including both models into the average output as separate entities to let choose only the relevant one?

**Pull request closed without merging**
