### PR TITLE
Add support for ORNO WE-504

### PR DESCRIPTION
**Pull request by bbiegun**
This is to add support of ORNO WE-504. It's implementing #182 .

### CODE REVIEW

**Comment by andig** [comment]
Could you run `mbmd docs` and commit the updated program docs, too?

**Comment by andig** [comment]
Is there a WE 505 that should be supported, too as with the other ORNO meters?

**Comment by bbiegun** [comment]
Docs are regenerated. I added a space more to the listing so it'll not overlap. There is WE 505 but have no RS connection. For now there is no more Orno meters with RS ports.

**Comment by andig** [comment]
I'm a bit confused now. You're saying this implementation supports 504/514/515? Shouldn't that replace https://github.com/volkszaehler/mbmd/blob/master/meters/rs485/orno1p.go then instead of adding a new file?

**Comment by bbiegun** [comment]
Unfortunately not. 1 phase meters added previously have different registers
and scaling. There is even a different program just to handle this one. I
wasn't aware previously then was supprised too when bought 504.

pt., 18 gru 2020, 09:05 użytkownik andig <notifications@github.com> napisał:

**Pull request merged**
