### PR TITLE
SDM72 power measurement support

### PR DESCRIPTION
**Pull request by pdcleyn**
The Eastron SDM72 also has an aggregated Power measurement besides the overall Import and export measurements.

### CODE REVIEW

**Comment by andig** [comment]
Could you check if #31 works for you? I've added a couple more registers.

I would also be very interested in how #29 works on devices that support less registers than implemented now, e.g. with the SDM 120. (ping @mreschka).

**Comment by pdcleyn** [comment]
@andig #31 works for me as well, so I'll close this PR. SDM 72 only implements Total import and export next to total power. So I guess this also answer your question wrt devices implementing less registers. 

I'm storing measurements in influx and as you map every measurement in different tags, it will have more impact on memory usage compared to storing them in different fields in a single metric.

**Comment by andig** [comment]
@pdcleyn could you share a logfile of what happens when mbdm tries to read a measurement that doesn't exist for your meter? I only have a 630, so I can't check. Thanks!

**Comment by andig** [comment]
ping @pdcleyn your help would be highly appreciated

**Pull request closed without merging**
