### PR TITLE
improve mbmd run description for InfluxDB 1.8

### PR DESCRIPTION
**Pull request by BMOD89**
Clarify description for InfluxDB 1.8

### CODE REVIEW

**Review by andig — COMMENTED** [review]
Not sure this is needed. If you don‘t have a specific setting why mention that you don‘t have to use it?

**Comment by BMOD89** [comment]
I struggled with this settings a bit and had to read the documentation of the influxdb go client (https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility) 
Other parameters like influx-token are also marked as optional...

**Comment by andig** [comment]
The organization is optional (I think just the comment is wrong). Token is also optional and will be replaced by user/password:

	// InfluxDB v1 compatibility
	if token == "" && user != "" {
		token = fmt.Sprintf("%s:%s", user, password)
	}

**Comment by andig** [comment]
Closing here- shouldn'd be necessary with v1.4 influx client

**Pull request closed without merging**
