### PR TITLE
Allow accessing subdevices by specifying subdevice id as slave.subdevice

### LINKED ISSUE #128: SolarEdge SE10K
Hi, 

ich wollte mbmd für meinen SolarEdge SE10K einsetzen um die Daten an eine InfluxDB zu schicken. Leider komme ich nicht voran. 

Der inspect-Befehl gibt folgendes aus: 
<details>
  <summary>Ausgabe</summary>

```
/ # mbmd inspect -v -d SOLAREDGE:1@192.168.100.24:502
2020/05/31 17:25:47 config: creating TCP connection for 192.168.100.24:502
--------- Model 1 common ---------
Mn         SolarEdge     string
Md              SE10K    string
Opt                      string
Vr           0003.225    string
SN           7E14903B    string
DA               1.00    uint16
Pad            0x0067    pad
--------- Model 103 inverter ---------
A                    2.49    uint16
AphA                 0.81    uint16
AphB                 0.85    uint16
AphC                 0.82    uint16
A_SF                   -2    sunssf
PPVphAB            406.70    uint16
PPVphBC            409.20    uint16
PPVphCA            408.80    uint16
PhVphA             232.00    uint16
PhVphB             235.50    uint16
PhVphC             237.30    uint16
V_SF                   -1    sunssf
W                  360.00    int16
W_SF                   -1    sunssf
Hz                  49.98    uint16
Hz_SF                  -2    sunssf
VA                 584.90    int16
VA_SF                  -1    sunssf
VAr               -461.00    int16
VAr_SF                 -1    sunssf
PF                 -61.44    int16
PF_SF                  -2    sunssf
WH            17017776.00    acc32
WH_SF                   0    sunssf
DCA                  0.49    uint16
DCA_SF                 -4    sunssf
DCV                747.60    uint16
DCV_SF                 -1    sunssf
DCW                365.40    int16
DCW_SF                 -1    sunssf
TmpCab                n/a    int16
TmpSnk              40.43    int16
TmpTrns               n/a    int16
TmpOt                 n/a    int16
Tmp_SF                 -2    sunssf
St                      4    enum16
StVnd                   0    enum16
Evt1                  n/a    bitfield32
Evt2                  n/a    bitfield32
EvtVnd1        0x00000001    bitfield32
EvtVnd2               n/a    bitfield32
EvtVnd3               n/a    bitfield32
EvtVnd4        0x00000000    bitfield32
--------- Model 1 common ---------
Mn           WattNode    string
Md      WND-3Y-400-MB    string
Opt          Export+I    string
Vr                 31    string
SN            5007280    string
DA               1.00    uint16
Pad            0x00cb    pad
--------- Model 203 ac_meter ---------
A                            2.20    int16
AphA                         2.10    int16
AphB                         0.70    int16
AphC                         0.00    int16
A_SF                           -1    sunssf
PhV                        232.50    int16
PhVphA                     232.50    int16
PhVphB                     236.00    int16
PhVphC                     237.65    int16
PPV                       -247.70    int16
PhVphAB                   -249.68    int16
PhVphBC                   -246.92    int16
PhVphCA                   -246.50    int16
V_SF                           -2    sunssf
Hz                          49.99    int16
Hz_SF                          -2    sunssf
W                          -36.00    int16
WphA                       -15.00    int16
WphB                       -55.00    int16
WphC                        34.00    int16
W_SF                            0    sunssf
VA                         564.00    int16
VAphA                      281.00    int16
VAphB                      152.00    int16
VAphC                      144.00    int16
VA_SF                           0    sunssf
VAR                       -563.00    int16
VARphA                    -280.00    int16
VARphB                    -141.00    int16
VARphC                    -140.00    int16
VAR_SF                          0    sunssf
PF                           3.00    int16
PFphA                        3.70    int16
PFphB                       28.15    int16
PFphC                      -22.84    int16
PF_SF                          -2    sunssf
TotWhExp              12142959.00    acc32
TotWhExpPhA            5083589.00    acc32
TotWhExpPhB            5031494.00    acc32
TotWhExpPhC            4536532.00    acc32
TotWhImp               2051098.00    acc32
TotWhImpPhA            2118733.00    acc32
TotWhImpPhB             965564.00    acc32
TotWhImpPhC            1475456.00    acc32
TotWh_SF                        0    sunssf
TotVAhExp                     NaN    acc32
TotVAhExpPhA                  NaN    acc32
TotVAhExpPhB                  NaN    acc32
TotVAhExpPhC                  NaN    acc32
TotVAhImp                     NaN    acc32
TotVAhImpPhA                  NaN    acc32
TotVAhImpPhB                  NaN    acc32
TotVAhImpPhC                  NaN    acc32
TotVAh_SF                     n/a    sunssf
TotVArhImpQ1                  NaN    acc32
TotVArhImpQ1PhA               NaN    acc32
TotVArhImpQ1PhB               NaN    acc32
TotVArhImpQ1PhC               NaN    acc32
TotVArhImpQ2                  NaN    acc32
TotVArhImpQ2PhA               NaN    acc32
TotVArhImpQ2PhB               NaN    acc32
TotVArhImpQ2PhC               NaN    acc32
TotVArhExpQ3                  NaN    acc32
TotVArhExpQ3PhA               NaN    acc32
TotVArhExpQ3PhB               NaN    acc32
TotVArhExpQ3PhC               NaN    acc32
TotVArhExpQ4                  NaN    acc32
TotVArhExpQ4PhA               NaN    acc32
TotVArhExpQ4PhB               NaN    acc32
TotVArhExpQ4PhC               NaN    acc32
TotVArh_SF                    n/a    sunssf
Evt                    0x00000000    bitfield32
```

</details>

Soweit so gut, wenn ich jedoch den run-Befehl verwende, bekomme ich folgende Fehlermeldung: 

```
/ # mbmd run -v -d SOLAREDGE:1@192.168.100.24:502
2020/05/31 17:15:23 mbmd unknown version (unknown commit)
2020/05/31 17:15:23 config: creating TCP connection for 192.168.100.24:502
2020/05/31 17:15:23 config: declared device SOLAREDGE:1
2020/05/31 17:15:23 httpd: starting api at 0.0.0.0:8080
2020/05/31 17:15:23 initializing device SOLAREDGE1.1 failed: sunspec: multiple devices found
```
Wobei der Fehler immer wieder in einer Schleife kommt. 

Weiterhin habe ich versucht, per scan die angeschlossenen Geräte zu funden. 
Findet das Programm nichts: `2020/05/31 16:46:20 found 0 active devices:`

@andig hast du eine Idee woran es liegen könnte?

### LINKED ISSUE #135: Maintain device order
Hi,

I've set up `mbmd` for two SUNSPEC devices, a KOSTAL inverter (plenticore) and a smart meter device (ksem).

The corresponding device config looks like that:

```
adapters:
- device: 192.168.1.5:502
- device: 192.168.1.6:1502

devices:
- name: ksem
  type: SUNSPEC
  id: 71
  adapter: 192.168.1.5:502
- name: plenticore
  type: SUNSPEC
  id: 71
  adapter: 192.168.1.6:1502
```

The setup worked as expected, the KSEM ended up as `KOSTAL1.71`, the plenticore as `KOSTAL2.71` and `mbmd` started logging to influxdb. However, after a short downtime and restart, I've noticed that the devices got mixed up. The smart meter (KSEM) was now `KOSTAL2.71` and the inverter `KOSTAL1.71`. I've noticed this after an hour by looking at weird graphs. After restarting `mbmd`, the order was restored again.

Corresponding stdout:

```
# second run

2020/07/28 15:27:46 mbmd unknown version (unknown commit)
2020/07/28 15:27:46 config: using /etc/mbmd/config.yaml
2020/07/28 15:27:46 config: creating TCP connection for 192.168.1.5:502
2020/07/28 15:27:46 config: creating TCP connection for 192.168.1.6:1502
2020/07/28 15:27:46 config: declared device SUNSPEC:71
2020/07/28 15:27:46 config: declared device SUNSPEC:71
2020/07/28 15:27:46 httpd: starting api at 0.0.0.0:8080
2020/07/28 15:27:46 initialized device KOSTAL2.71: {KOSTAL KOSTAL Smart Ene  1.2.1 xxx}
2020/07/28 15:27:46 sunspec: device opened partially
2020/07/28 15:27:46 initialized device KOSTAL1.71: {KOSTAL PLENTICORE plus1          01.15.04 xxx}
2020/07/28 16:36:46 received signal - stopping
2020/07/28 16:36:46 stopped

# third run

2020/07/28 16:36:50 mbmd unknown version (unknown commit)
2020/07/28 16:36:50 config: using /etc/mbmd/config.yaml
2020/07/28 16:36:50 config: creating TCP connection for 192.168.1.5:502
2020/07/28 16:36:50 config: creating TCP connection for 192.168.1.6:1502
2020/07/28 16:36:50 config: declared device SUNSPEC:71
2020/07/28 16:36:50 config: declared device SUNSPEC:71
2020/07/28 16:36:50 httpd: starting api at 0.0.0.0:8080
2020/07/28 16:36:50 initialized device KOSTAL1.71: {KOSTAL KOSTAL Smart Ene  1.2.1 xxx}
2020/07/28 16:36:50 sunspec: device opened partially
2020/07/28 16:36:50 initialized device KOSTAL2.71: {KOSTAL PLENTICORE plus1          01.15.04 xxx}
```

I think the order should be maintained, so data doesn't get messed up.

Alternatively, an option to persistently naming the devices would suffice. As you can see, I've filled out the `name` field, however it doesn't seem to be respected anywhere. Maybe related to point 2 in #65?

Side question: is "device partially opened" something to be worried about?

### PR DESCRIPTION
**Pull request by andig**
Fix #128, fix #135, replaces #132.

/cc @BMOD89 @magpern @grmat

### CODE REVIEW

**Comment by grmat** [comment]
Hi,

this doesn't fix my issue in #135. I still get the devices mixed up, just the ID looks slightly different, instead of `KOSTAL1.71`, it's `KOSTAL1-71`.

KSEM still end's up as 1 or 2 sometimes and Plenticore as 2 or 1 respectively (without changing config or flag order of course). Or have I missed something? The new subdevice syntax doesn't apply for me, as my devices doesn't seem to expose subdevices. I query both as separate devices.

**Comment by andig** [comment]
@grmat seems you have a more complex setup than I have access to testing. Could you pm me at cpuidle@gmx.de for remote access?

**Comment by andig** [comment]
@grmat could you please retry?

**Comment by grmat** [comment]
I'm not able to reproduce the issue anymore.

**Pull request merged**
